### ISSUE TITLE
Package depends on R >= 4.1

### ISSUE THREAD

**Issue by JosiahParry** [Executive-Communications-Dataset/ecdata#4]
Here you declare that your package requires a minimum R version of 4.0 

https://github.com/Executive-Communications-Dataset/ecdata/blob/2a8de2017d46b7dc169b9deff8492d7ca267edfd/DESCRIPTION#L22

However, you use an anonymous function which wasn't introduced until R 4.1 

https://github.com/Executive-Communications-Dataset/ecdata/blob/2a8de2017d46b7dc169b9deff8492d7ca267edfd/R/zzz.R#L3

**Comment by joshuafayallen** [comment]
Great catch!  Bumped the minimal version in the description
