### ISSUE TITLE
example_scrapper should be example_scraper

### ISSUE THREAD

**Issue by JosiahParry** [Executive-Communications-Dataset/ecdata#5]
If I am reading this correctly this function gives you an example web scraper to use. 

https://github.com/Executive-Communications-Dataset/ecdata/blob/2a8de2017d46b7dc169b9deff8492d7ca267edfd/R/example_scrapper.R#L23C12-L23C12

However the function is called a scrapper as in someone who gets into scraps or fights. I think, however, you mean example 
(web) _scraper_.

**Comment by joshuafayallen** [comment]
Great catch! Renamed the function.
